spring:
  application:
    name: businessCase
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  datasource:
    name: tasks_s_e
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tasks_s_e
    username: root
    password: Gersin4282
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
server:
  port: 8080
